CREATE TABLE IF NOT EXISTS Uat(
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL,
	siruta INTEGER NULL,
	Judete_id INTEGER, --FK
	FOREIGN KEY (Judete_id) REFERENCES Judete
	
);

SELECT * FROM Uat